# Generated by Django 4.2.21 on 2025-05-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_stage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='jobs.jobapplication'),
        ),
    ]
