# Generated by Django 4.2.21 on 2025-05-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_stage_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.jobapplication'),
        ),
    ]
